jungle-6-3/code-sync-be

package.json
pnpm-lock.yaml
src/app.module.ts

초기 셋팅입니다.
.env 파일에 mysql 기본 셋팅과 JWT secert키가 있습니다.
DATABASE는 mysql로 설정 했습니다.
Swagger 설정은 아직 미진행입니다.
- closes #1

init project setting: socket.io, typeORM, mysql, JWT, Swagger

---

src/main.ts

main에 swagger api 설정.
- close #4

feat: init swagger setting

---

src/app.module.ts
src/conversation-events/conversation-events.gateway.ts
src/conversation-events/conversation-events.module.ts
src/conversation-events/dto/create-conversation-event.dto.ts
src/conversation-events/dto/update-conversation-event.dto.ts
src/conversation-events/events/chatting.gateway.ts
src/conversation-events/events/shared-doc.gateway.ts
src/conversation-events/events/voice.gateway.ts
src/conversation-events/interfaces/room-socket.interface.ts
src/conversations/conversations.controller.ts
src/conversations/conversations.module.ts
src/conversations/conversations.service.ts
src/conversations/dto/create-conversation.dto.ts
src/conversations/dto/update-conversation.dto.ts
src/conversations/entities/conversation.entity.ts
src/rooms/dto/create-room.dto.ts
src/rooms/dto/update-room.dto.ts
src/rooms/entities/room.entity.ts
src/rooms/rooms.controller.ts
src/rooms/rooms.interface.ts
src/rooms/rooms.module.ts
src/rooms/rooms.service.ts

---
모듈화로 작업하기 위해 파일 생성
- closes #8

feat: add module files

---

src/exceptio-global.filter.ts
src/main.ts

[BE] feat: setGlobalPrefix

---

src/main.ts

feat: add enableCors

---

src/auth/auth.module.ts
src/auth/auth.service.ts

auth service에서 jwt를 decode해주는 코드 작성
closes #20

[BE] feat: make getUser

---

src/users/users.service.ts

JwtPayloadDto로 user의 pk를 얻기 위한 findUserPk 함수 작성
closes #21

[BE] feat: findUserPk

---

src/auth/auth.controller.ts
src/auth/auth.filter.ts
src/auth/auth.service.ts
src/exceptio-global.filter.ts
src/users/users.controller.ts
src/users/users.filter.ts
src/validate-global.pipe.ts

기존에 있던 디버깅용 콘솔 제거했습니다.
유저와 인증 컨트롤로에 커스텀 필터를 적용했습니다. 이로 인해 jwt 인증 관련 예외처리를 커스텀 했습니다.
closes #24

[BE] Feat: add global filter and remove debug console

---

package.json
pnpm-lock.yaml

socket.io  pakage 추가
closes #34

[BE] chore socket.io pakage

---

src/rooms/rooms.module.ts

RoomsModule에 import 잘못 하던 것 수정
거 미안하게 됐수다
closes

fix: change import in RoomsModule

---

src/conversation-events/conversation-events.gateway.ts

WebSocketGateway에 react server에 대한 cors 추가
closes

fix: add cors in WebSocketGateway

---

src/conversation-events/conversation-events.gateway.ts

fix: change cors to allow all origin

---

src/conversation-events/conversation-events.gateway.ts

cors륾 리액트 서버만 허용하도록 수정 수정
closes #52

fix: change cors

---

src/conversation-events/conversation-events.gateway.ts
src/conversation-events/events/chatting.gateway.ts
src/conversation-events/events/shared-doc.gateway.ts
src/conversation-events/events/voice.gateway.ts

다른 gateway도 cors 허용하도록 수정
closes

fix: try socket cors error

---

src/app.module.ts
src/conversation-datas/conversation-datas.controller.ts
src/conversation-datas/conversation-datas.module.ts
src/conversation-datas/conversation-datas.service.ts

기존 s3 폴더 이름 conversation-datas로 변경
closes #54

[BE]fix: rename s3 to conversation-datas

---

src/conversation-datas/data/chatting.ts

- 채팅을 저장할 chats queue 구현
- queue의 json을 string으로 변환하는 function 구현
closes

[BE] feat: create chatdata class for save chat

---

src/conversation-events/conversation-events.filter.ts
src/conversation-events/conversation-events.gateway.ts

웹 소켓 필터 추가
쿠키 확인 시 undefined인지 보도록 수정
closes #44

[BE] Feat/44 Add global filter of websocket

---

src/auth/auth.service.ts

AuthExceptionError에 에러코드 추가
closes

fix: add error code in AuthExceptionError

---

src/auth/auth.controller.ts

- cookie secure => true로 변경
- coocke sameSite=> none으로 설정
closes #65

fix: change cookie strategy

---

src/auth/auth.controller.ts

localhost: 5173 포트에 쿠키  전송 가능하도록 추가
closes

[BE] fix: add domain for cookie

---

src/main.ts

[BE] fix: add credentials true

---

src/auth/auth.controller.ts

res.cookie 를 다른 도메인으로 보낼 수 있도록 만든 코드 삭제
closes

[BE] fix: delete domain code

---

src/conversation-events/conversation-events.filter.ts
src/conversation-events/conversation-events.gateway.ts
src/conversation-events/interfaces/room-socket.interface.ts
src/rooms/rooms.controller.ts
src/users/users.service.ts

방 참여 관련 API 수정
#43 이건 스켈레톤만 짜고 webRTC 작동 확인 후 자세히 작성할 계획
closes #71

[BE] 웹소캣 API 리팩토링

---

src/rooms/rooms.service.ts
src/utils/exception-global.filter.ts

refector: room uuid API 수정

---

src/conversation-events/conversation-events.gateway.ts

feat: webRtc

---

src/conversation-events/conversation-events.gateway.ts

logger 많이 추가
방에 join하도록 수정
closes

fix: 방에 join하도록 수정

---

src/conversation-events/conversation-events.gateway.ts

fix: user pk 못 찾는 에러 수정 시도

---

src/app.module.ts
src/conversation-datas/conversation-datas.controller.ts
src/conversation-datas/conversation-datas.module.ts
src/conversation-datas/conversation-datas.service.ts
src/conversation-datas/data/chatting.ts
src/conversation-datas/dto/save-data.dto.ts
src/conversation-datas/entities/conversations-data.entity.ts

- Data 저장시 필요한 DTO 생성
- ConversationDatas 엔티티 수정
- chatting 정보 저장 기능 구현
closes #83

[BE] Feat: 코드리뷰 DB에 저장하기 위한 기능구현(1차)

---

src/conversation-events/conversation-events.filter.ts
src/conversation-events/conversation-events.gateway.ts

async 함수를 호출하고 await를 하지 않아 error가 나중에 handling된 것을 처리함
closes #85

fix: async 함수에 await를 하지 않아 error를 throw하지 않던 문제 수정

---

src/auth/auth.controller.ts

fe localhost에 쿠키 추가하는 코드 추가
closes #99

[BE]fix: add localhost cookie

---

src/auth/auth.controller.ts

[BE] fix: cookie 도메인 수정

---

src/auth/auth.controller.ts

cookie 설정을 위한 도메인을 다시 삭재한다.
closes

[BE] fix:원상복귀

---

src/conversation-events/conversation-events.gateway.ts
src/conversation-events/events-handler/room.service.ts

WebSocket에서 reject-user와 user-disconnected 추가
한 쪽이 disconnect되면 나머지도 disconnected 되도록 수정
closes #96

[BE ]Feat/96 WebSocket에서 reject-user와 user-disconnected 추가

---

src/conversation-events/conversation-events.gateway.ts
src/conversation-events/pipes/validate-user-is-creator.pipe.ts
src/conversation-events/pipes/validate-user-is-joining.pipe.ts

방장인지 확인하는 pipe와 대화 중인지 확인하는 pipe 구현
Gateway에서 user 권한 확인하는 작업을 pipe로 교체
closes #90

[BE] Feat/90 Gateway에서 user 권한 확인하는 작업을 pipe로 교체

---

src/conversation-events/events-handler/peer-js.service.ts
src/conversation-events/events-handler/room.service.ts
src/conversation-events/interfaces/room-socket.interface.ts
src/rooms/rooms.controller.ts
src/rooms/rooms.service.ts

RoomsService에 roomsByPk 삭제하며 Gateway 포함해서 관련 logic도 삭제
같은 uuid에 같은 user가 요청한 경우, 이전 연결을 끊고 이전과 같은 상태의 연결을 하도록 수정
closes #104 #88

[BE] Refactor/104

---

src/conversation-events/conversation-events.gateway.ts
src/conversation-events/events-handler/peer-js.service.ts
src/conversation-events/events-handler/room.service.ts
src/conversation-events/interfaces/on-server-init.interface.ts

Server 소켓을 다른 service에게 DI 하도록 변경
service의 method를 호출할 때 server는 인자로 안 넘겨주는 것으로 변경
closes #109

[BE] Refactor/109 Server 소켓을 다른 service에게 DI 하도록 변경

---

src/conversation-events/conversation-events.gateway.ts
src/conversation-events/events-handler/peer-js.service.ts
src/conversation-events/events-handler/room.service.ts
src/conversation-events/interfaces/on-server-init.interface.ts

AfterServerInit에서 server를 인자로 넘겨주도록 수정
closes

[BE] Refactor: AfterServerInit에서 server를 인자로 넘겨주도록 수정

---

src/conversation-events/conversation-events.gateway.ts
src/conversation-events/events-handler/events-handler.module.ts
src/conversation-events/events-handler/peer-js.gateway.ts

refactor: check okay if gateway is moved

---

src/conversation-events/conversation-events.gateway.ts
src/conversation-events/events-handler/peer-js.gateway.ts
src/conversation-events/events-handler/room.gateway.ts

겁나 많은 것이 한 번에 봐달라고 하는 것은 매우 실례되는 일인 것은 알지만,
전반적인 피드백을 받고 싶어서 리뷰 요청 합니다.
closes

refactor: gateway가 init될 때 logger 출력물 변경

---

src/conversation-datas/data/chatting.ts
src/conversation-events/events-handler/chatting-handler.gateway.ts
src/conversation-events/events-handler/events-handler.module.ts
src/rooms/room.ts

- chatting-gateway 구현
- room에서 data 객체 타입 추가.
- - 인터페이스로 이후에 쓸 타입 선언
- chatData에서 data를 리스트에 저장할 수 있게 코드 수정
- 화이팅!
closes #115

[BE] Feat: 채팅기능을 구현한다.

---

src/conversation-events/dto/create-message.ts
src/conversation-events/events-handler/chatting-handler.gateway.ts

chatting이 들어왔을 경우 message 를 callback으로 리턴
closes

fix: 콜백함수로 메시지를 리턴한다.

---

src/conversation-datas/data/chatting.ts
src/conversation-events/dto/create-message.ts
src/conversation-events/events-handler/chatting-handler.gateway.ts

msg를 broadcast로 전송하고 callback 함수를 인자로 받아서 실행하는 기능 구현
closes

fix: callback 함수 실행

---

src/conversation-events/dto/create-message.ts
src/conversation-events/events-handler/chatting-handler.gateway.ts

chatting gateway 로거 등록, message 객체 전송 수정한다.
chattingGateway 시작점 로거 등록
message 객체가 message{message:''} 로 나오는문제 수정을 위해 msg= message.message로 message 객체 꺼내서 사용
closes

[BE]Feat: chatting gateway 로거 등록, message 객체 전송 수정한다.

---

src/conversation-datas/entities/conversations-data.entity.ts
src/conversations/entities/conversation.entity.ts
src/users/entities/user.entity.ts

Conversation Entity 생성
이에 맞는 User, ConversationDatas의 엔티티 추가 및 연관관계 생성
closes

[BE]Feat: Conversaion Entity를 생성한다.

---

src/conversations/conversations.service.ts
src/conversations/dto/conversation-response.dto.ts
src/conversations/dto/conversation.dto.ts
src/conversations/dto/create-conversation.dto.ts
src/conversations/dto/update-conversation.dto.ts

- Conversations Entity 작성
- 저장하거나 보낼때 사용할 ConversationDTO 작성, 회의목록 Response로 ConversationData[] 사용
- createConversationDto 삭제 -> ConversationDTO와 중복
closes #132

[BE] Feat: Conversation Entity / DTO 를 작성한다.

---

src/conversation-events/conversation-events.gateway.ts
src/conversation-events/conversation-events.service.ts
src/conversation-events/events-handler/peer-js.gateway.ts
src/conversation-events/events-handler/room.gateway.ts
src/conversation-events/interfaces/room-socket.interface.ts
src/conversation-events/interfaces/socket-information.interface.ts
src/rooms/room.ts
src/rooms/rooms.service.ts

처음 생성과, closing에서 저장 안 하면 30분 내에 삭제
중간에 나갈 때 5분 이내에 재접 안 하면 closing
creator가 방 터트린다 신호 보내면 closing
closes #116

[BE] Feat/116 방 생명주기 구현

---

src/conversation-events/conversation-events.service.ts
src/conversation-events/events-handler/room.gateway.ts

재진입 시 invite-accepted를 emit하도록 수정
invite-accepted에 role을 추가로 보내도록 수정
#138 
closes

[BE] fix: 재진입 시 invite-accepted를 emit하도록 수정

---

src/conversation-events/conversation-events.service.ts

fix: joinClientInRoom에서 emit하는 것을 2초 되에 하는 것으로 수정

---

src/auth/auth.service.ts
src/utils/global-http-exception.ts

custom exception의 구조가 같기때문에 각 도메인에서 만들지 않고 global로 만들어서 사용한다.
closes

[BE] fix: authException을 globalHttpException으로 변경한다.

---

src/conversation-events/conversation-events.gateway.ts
src/conversation-events/conversation-events.module.ts
src/conversation-events/conversation-events.service.ts
src/conversation-events/events-handler/events-handler.module.ts
src/conversation-events/events-handler/room.gateway.ts
src/conversation-events/interfaces/room-socket.interface.ts
src/conversation-events/interfaces/socket-information.interface.ts
src/conversation-events/pipes/validate-user-is-joining.pipe.ts
src/rooms/item/index.ts
src/rooms/item/room-event.ts
src/rooms/item/room-event/index.ts
src/rooms/item/room-event/room-event.module.ts
src/rooms/item/room-event/room-event.service.ts
src/rooms/room-events.service.ts
src/rooms/rooms.controller.ts
src/rooms/rooms.module.ts
src/rooms/rooms.service.ts

Rooms에 몰려있는 것 일부를 RoomEvent로 분리
#137 
closes

[BE] Refactor/137 Rooms에 몰려있는 것 일부를 RoomEvent로 분리

---

src/conversation-datas/dto/conversation-data-save.dto.ts
src/conversations/dto/room-save.dto.ts

-Room에서 회의 기록과 회의 자료를 저장하기위한 dto 작성
- Conversation에서 Room에서 받은 데이터중 conversationdata에 저장할 dto작성
closes #

[BE] Feat: 회의를 저장하기위한 DTO를 구현한다.

---

src/auth/auth.controller.ts
src/conversations/dto/conversation-save.dto.ts

쿠키 age를 수정하는 방식에서 clear하는 방식으로 수정
closes

fix: logout시 쿠키 삭제 로직 수정

---

src/auth/auth.controller.ts

httpOnly옵션과 secure, sameSite 옵션 추가
closes

fix: 쿠키 삭제 옵션 설정

---

src/conversation-events/conversation-events.module.ts
src/conversation-events/conversation-events.service.ts
src/conversation-events/events-handler/events-handler.module.ts
src/conversation-events/room-handler.gateway.ts
src/conversation-events/server-join-handler/save-voice.service.ts
src/conversation-events/server-join-handler/save-yjs.service.ts
src/conversation-events/server-join-handler/server-join-handler.module.ts
src/conversation-events/server-join-handler/server-join-handler.service.ts
src/rooms/item/room-event/index.ts
src/rooms/item/room-event/room-event.module.ts
src/rooms/item/room-event/room-event.service.ts

server가 room에 join하는 module 추가
closes #156

[BE] Feat/156 server가 room에 join하는 module 추가

---

src/conversations/conversations.controller.ts
src/conversations/conversations.service.ts

쿼리로 페이지 인자를 받고 보내줄 페이지요소 8개만 읽어서 사용자에게 보내주는 기능 구현
closes #157

[BE[ Refactoring: 회의 목록 기능에 페이지네이션 구현

---

src/conversation-events/conversation-events.service.ts

상대방이 나갈 때 user-disconnected event로 보내야 했던 오타 수정
closes

fix: user-disconnected 오타 수정

---

.github/workflows/api-cd.yaml
src/conversation-datas/conversation-datas.controller.ts
src/conversation-datas/conversation-datas.module.ts
src/conversation-datas/conversation-datas.service.ts
src/conversation-datas/data/fileconfig.ts
src/conversation-datas/dto/file-info.dto.ts
src/conversation-datas/dto/save-data.dto.ts
src/conversation-datas/entities/conversations-data.entity.ts
src/conversation-datas/file-upload.service.ts
src/conversation-events/conversation-events.service.ts
src/conversations/conversations.service.ts
src/conversations/entities/conversation.entity.ts

room-save dto를 가지고 conversation과 conversationdatas를 저장한다.
예상 흐름
room: save-event -> conversation: parse conversation event -> conversation: createConversationDatas call -> conversationdatas-> fileUpload to s3 and save result and  save conversation shared info -> conversation save
closes #151

[BE]Feat: 회의기록 저장 기능을 구현한다.

---

src/conversation-datas/dto/conversation-data-save.dto.ts
src/conversation-events/conversation-events.service.ts
src/conversation-events/events-handler/chatting-handler.gateway.ts
src/conversations/conversations.module.ts
src/rooms/item/room-event/room-event.service.ts
src/rooms/rooms.controller.ts
src/rooms/rooms.module.ts
src/rooms/rooms.service.ts
src/users/users.service.ts

[BE] Refactor/166 room 생명 주기 정책 수정

---

src/conversation-events/interfaces/room-socket.interface.ts

disconenctRoomSocket에서 closing일 때 room-closed를 creator에게 emit하지 않도록 수정
closes

[BE] disconenctRoomSocket에서 closing일 때 room-closed를 creator에게 emit하지 않도록 수정

---

src/conversation-datas/data/chatting.ts
src/conversation-datas/data/save-data-dto-convesation.interface.ts
src/conversation-events/events-handler/chatting-handler.gateway.ts
src/rooms/rooms.service.ts

saveRoom에서 체팅 저장하게 변경
closes #170

[BE] Feat/170 saveRoom에서 체팅 저장하게 변경

---

src/conversation-datas/dto/conversation-data-save.dto.ts
src/conversation-datas/file-upload.service.ts
src/conversations/conversations.controller.ts
src/conversations/dto/room-save.dto.ts

fileupload 할때 utf-8 인코딩
closes #176

[BE] Fix : s3에 업로드 할때 utf-8 인코딩 구현하기

---

src/auth/auth.service.ts
src/conversation-datas/conversation-datas.service.ts
src/conversation-datas/file-upload.service.ts
src/conversations/conversations.service.ts
src/utils/global-http-exception.ts

GlobalHttpException 수정
ConversationDatas, UploadFile error제어
closes #178

[BE] Refactor : GlobalHttpException의 status를 커스텀한다.

---

src/conversation-datas/conversation-datas.service.ts
src/conversation-datas/data/fileconfig.ts
src/conversation-datas/dto/conversation-data-save.dto.ts
src/rooms/rooms.service.ts

draw 관련된 파일들 drawBoard로 이름 변경
closes #180

[BE] Refactor: draw객체 이름을 drawBoard로 변경

---

package.json
pnpm-lock.yaml
src/app.module.ts
src/conversation-datas/data/drawBoard.ts
src/conversation-datas/data/save-data-dto-convesation.interface.ts
src/conversation-events/conversation-events.service.ts
src/conversation-events/room-handler.gateway.ts
src/conversation-events/server-join-handler/save-voice.service.ts
src/conversation-events/server-join-handler/save-yjs.service.ts
src/conversation-events/server-join-handler/server-join-handler.module.ts
src/conversation-events/server-join-handler/server-join-handler.service.ts
src/rooms/item/index.ts
src/rooms/item/room-event/room-event.service.ts
src/yjs/yjs-doc-provider.interface.ts
src/yjs/yjs.module.ts
src/yjs/yjs.service.ts

room에서 yjs 데이터 다루게 하기
closes #161

[BE] Feat/161 room에서 yjs 데이터 다루게 하기

---

src/conversation-datas/data/drawBoard.ts
src/conversation-events/server-join-handler/save-yjs.service.ts
src/conversation-events/server-join-handler/server-join-handler.service.ts
src/rooms/item/index.ts
src/rooms/rooms.service.ts

saveRoom에서 SaveDataDto에 yjs 내용 저장하게 하기
closes #171

[BE] Feat/171 saveRoom에서 SaveDataDto에 yjs 내용 저장하게 하기

---

src/auth/auth.service.ts

[BE] bug: 회원가입 중복 로그인 검증

---

src/conversation-events/room-handler.gateway.ts

close-room event일 때 room의 status 확인하도록 수정
closes

fix: close-room event일 때 room의 status 확인하도록 수정

---

package.json
pnpm-lock.yaml
src/conversation-datas/conversation-datas.module.ts
src/conversation-datas/conversation-datas.service.ts
src/conversation-datas/dto/update-conversation-data.dto.ts
src/conversation-datas/entities/conversations-data.entity.ts
src/conversation-datas/s3.service.ts
src/conversations/conversations.controller.ts
src/conversations/conversations.service.ts

- 회의 자료를 위한 preSignedUrl을 발급한다.
- conversation-datas entity이름 수정
- file upload 이름 s3로 변경
closes #186

[BE] Feat: conversationdata 호출 api 를 작성한다.

---

src/conversations/conversations.service.ts

conversations 요청에 sharedUuid, canShared 데이터 추가
closes

refactor: conversation 요청 canshared, sharedUuid 데이터 추가

---

src/conversation-datas/conversation-datas.controller.ts
src/conversation-datas/conversation-datas.service.ts

- 회의록 중 변경사항이 있는 데이터만 수정하도록 변경
- 이 후 수정할 데이터만 변경할 수 있도록 type을 변경해야함
closes #173

[BE] Feat: 이전 회의록 수정용 테스트 api를 작성한다.

---

src/yjs/yjs.service.ts

drawBoard를 제대로 저장하도록 수정
closes

[BE] fix: drawBoard를 제대로 저장하도록 수정

---

src/conversation-datas/conversation-datas.service.ts
src/conversation-datas/data/fileconfig.ts
src/conversation-datas/dto/conversation-data-save.dto.ts
src/conversation-datas/entities/conversations-data.entity.ts
src/rooms/rooms.service.ts

Dto 및 FileConfig 수정
관련 코드 수정
엔티티 수정
closes #191

[BE]Refactor: CodeEdit을 저장할 수 있도록 엔티티와 Dto관련 코드 수정

---

src/rooms/rooms.service.ts
src/yjs/yjs.service.ts

getDrawBoardDoc에서 assets도 복사하도록 수정
closes #198

[BE] Bug/198 image를 저장하지 않던 문제 수정

---

src/conversation-datas/data/chatting.ts

interface chat을 Chat으로 변경
closes

[BE] fix: interface chat을 Chat으로 변경

---

src/conversation-datas/conversation-datas.service.ts
src/conversation-datas/data/fileconfig.ts
src/conversation-datas/dto/conversation-data-save.dto.ts
src/conversation-datas/dto/file-info.dto.ts
src/conversation-datas/s3.service.ts
src/rooms/rooms.service.ts

roomsaveDto에 codeEditor 추가
회의 종료 후 voice 의 s3Key 저장
closes

[BE] refactor: conversation Data Update와 create 로직을 최적화 한다.

---

src/conversation-datas/conversation-datas.service.ts
src/conversation-datas/data/fileconfig.ts
src/conversation-datas/dto/response-conversation-data.dto.ts
src/conversation-datas/dto/response-update-conversation-data.dto.ts
src/conversation-datas/entities/conversations-data.entity.ts
src/conversations/conversations.controller.ts
src/conversations/conversations.service.ts

- converseationData 수정 데이터 보는 service와 conversationData 데이터를 보는 service 로직을 일관성 있게 작성함.
- canshared가 없을 경우에는 exception처리
#208 
closes #189

[BE] Feat: sharedUuid로 회의록을 보는 기능 구현

---

src/conversation-datas/conversation-datas.service.ts

fix: conversationData의 공유 여부 확인하는 조건 삭제한다.

---

src/conversation-datas/conversation-datas.controller.ts
src/conversation-datas/conversation-datas.service.ts
src/conversation-datas/dto/update-conversation-data.dto.ts
src/conversations/conversations.controller.ts
src/conversations/conversations.service.ts
src/conversations/dto/update-conversationdatas.dto.ts

conversation-datas로 작성한 api를 conversations으로 이동
title 변경 가능하게 로직 수정
수정 api 요청 시 사용자 권환 확인
closes #208

[BE] Feat: 회의록 변경 시 유저의 권한을 확인한다. title 변경 기능을 구현한다.

---

src/conversation-datas/data/voice-chatting.ts
src/conversation-events/events-handler/voice-chat.gateway.ts

VoiceChat의 date type을 string으로 변경
closes

[BE] fix: VoiceChat의 date type을 string으로 변경

---

src/app.module.ts
src/open-ai/open-ai.controller.ts
src/open-ai/open-ai.module.ts
src/open-ai/open-ai.service.ts
src/open-ai/prompt.ts

openai 관련 module 구현
closes #214

[BE] Feat/214 openai 관련 module 구현

---

package.json
pnpm-lock.yaml
src/conversation-datas/data/voice-chatting.ts
src/open-ai/open-ai.module.ts
src/open-ai/open-ai.service.ts
src/open-ai/prompt.ts
src/rooms/rooms.module.ts
src/rooms/rooms.service.ts

OpenAiService에서 음성 채팅 내용을 변환 및 요약 기능 추가
하지만 돈 없는 그지기도 하고, 원본 음성 data를 얻기 위해 ai 작동 안 하게 함.
closes #206

[BE] Feat/206 voice를 저장하기 전에 변환하고 요약하는 기능 추가

---

src/open-ai/open-ai.service.ts
src/open-ai/prompt.ts

beautify 부분에서 틀린 부분만 찾는 형식으로 로직 변경
promt를 설정하는 부분에서 sytem 뿐만 아니라 다른 모든 것도 setting하고 text만 인자로 받는 함수로 변경
ai 성능 좋도록 promt 개선
closes

[BE] Refactor/220 stt를 문맥에 맞게 전환하는데 돈을 덜 쓰기 위해서 로직 변경

---

src/open-ai/open-ai.service.ts

console.log 삭제
beautifyVoiceChatChunk에서 고쳐진 chat을 탐색할 때, 복잡도가 작은 함수 주석으로 추가
(성능 차이를 느끼지 못 해서 주석으로 추가)
closes

[BE] Fix: console.log 삭제

---

src/open-ai/open-ai.service.ts

음성 채팅 내용 요약하는 기능 부착
전환하는 것은 붙이지 않음
closes

[BE] fix: 대화 요약하는 기능 부착

---

src/conversations/dto/update-conversationdatas.dto.ts

UpdateConversationDatasDto의 tilte에 ApiProperty를 적용한다.
closes

refactor: swagger적용을 위한 Apiproperty를 적용한다.

---

src/conversation-datas/conversation-datas.service.ts
src/conversation-datas/dto/response-update-conversation-data.dto.ts
src/conversations/conversations.service.ts

[BE] refactor: conversationDatas에 title을 같이 return 한다.

---

src/main.ts

body의 json을 parsing할 때 최대 50MB까지 허용하도록 수정
closes

[BE] fix: body의 json을 parsing할 때 최대 50MB까지 허용하도록 수정

---

package.json
pnpm-lock.yaml

express pakage 설치 안 되던 것 설치
closes

[BE] chore: express pakage 설치

---

src/conversation-datas/conversation-datas.service.ts

conversationDatas에서  Conversation을 leftjoin하고 여기에서 title을 가지고 온다.
closes #230

[BE] fix: join을 통해서 conversation의 title을 가지고온다.

---

src/conversation-datas/data/fileconfig.ts

[BE] fix: summary 오타 수정

---

src/conversations/conversations.service.ts

fix: summary getconversationdata에 추가

---

src/conversations/conversations.service.ts

refactor: getconversationDatas return 수정

---

src/conversation-datas/data/fileconfig.ts

refactor: UpdateType애 summary추가

---

src/rooms/item/room-event/room-event.service.ts

[BE] fix: close-room할 때, creator에세 room-closed emit하는 것 제거

---

src/conversation-datas/data/chatting.ts
src/conversation-datas/data/codeEditor.ts
src/conversation-datas/data/drawBoard.ts
src/conversation-datas/data/note.ts
src/conversation-datas/data/voice-chatting.ts

data dto에서 isShared의 default 값을 true로 변경
closes

[BE] fix: data dto에서 isShared의 default 값을 true로 변경

---

src/auth/auth.service.ts
src/users/users.service.ts

기존 entity에서 email에 unique를 설정해서 중복된 이메일이 들어올 공유 에러를 처리하는 방식에서
email로 user을 find 해서 있을경우 false 하는 방식으로 수정
closes #247

[BE] fix: user을 email을 기준으로 find 해서 중복 여부를 확인한다.

---

src/users/users.service.ts

fix: 이메일 중복여부 조건문 수정

---

src/rooms/rooms.controller.ts
src/users/users.controller.ts

users/me와 room/create/:prUrl swagger API 추가
closes

[BE] feat: swagger api 추가
